#!/usr/bin/env bash
set -e -x

SHIPS="tangaroa polarstern"

case "$1" in
alcf)
	for ship in $SHIPS; do
		for lidar in $(cat input/$ship/lidars); do
			parallel alcf lidar $lidar input/$ship/$lidar/{} data/$ship/{}/$lidar/plain/ output_sampling: 3600 tres: 225 noise_removal_sampling: 225 :::: input/$ship/voyages
		done
	done
	;;

weather)
	bin/tan1802_clouds input/tangaroa/tan1802/weather.csv data/tangaroa/tan1802/weather.nc
	parallel bin/polarstern_clouds input/polarstern/weather/{}.tsv data/polarstern/{}/weather.nc :::: input/polarstern/voyages
	;;

prepare_data)
	for ship in $SHIPS; do
		for lidar in $(cat input/$ship/lidars); do
			parallel mkdir -p data/$ship/{}/$lidar/all :::: input/"$ship"/voyages
			parallel mkdir -p data/$ship/{}/$lidar/train/samples :::: input/"$ship"/voyages
			parallel mkdir -p data/$ship/{}/$lidar/val/samples :::: input/"$ship"/voyages
			parallel mkdir -p data/$ship/{}/$lidar/pred/samples :::: input/"$ship"/voyages
		done
		mkdir -p data/all data/{train,val,pred}/samples
	done
	;;

prepare_samples)
	for ship in $SHIPS; do
		for lidar in $(cat input/$ship/lidars); do
			parallel bin/prepare_samples data/$ship/{}/$lidar/plain data/$ship/{}/weather.nc data/$ship/{}/$lidar/all :::: input/$ship/voyages
		done
	done
	;;

prepare_train_val_per_voyage)
	for ship in $SHIPS; do
		for voyage in $(cat input/$ship/voyages); do
			for lidar in $(cat input/$ship/lidars); do
				dir=data/$ship/$voyage/$lidar
				ls $dir/all/*T*.nc | shuf > $dir/all/files
				n=$(wc -l $dir/all/files | cut -d' ' -f1)
				nval=$(echo "print(round($n*0.2))" | python3)
				head -n $nval $dir/all/files > $dir/all/files_val
				tail -n +$(($nval+1)) $dir/all/files > $dir/all/files_train
				rm $dir/train/samples/*T*.nc || true
				rm $dir/val/samples/*T*.nc || true
				parallel ln -s ../../all/{/} $dir/train/samples/{/} :::: $dir/all/files_train
				parallel ln -s ../../all/{/} $dir/val/samples/{/} :::: $dir/all/files_val
			done
		done
	done
	;;

prepare_train_val)
	rm data/all/*T*.nc || true
	for ship in $SHIPS; do
		for voyage in $(cat input/$ship/voyages); do
			for lidar in $(cat input/$ship/lidars); do
				parallel ln -s ../../{} data/all/${ship}_${voyage}_${lidar}_{/} ::: data/$ship/$voyage/$lidar/all/*T*.nc
			done
		done
	done
	dir=data
	ls $dir/all/*T*.nc | shuf > $dir/all/files
	n=$(wc -l $dir/all/files | cut -d' ' -f1)
	nval=$(echo "print(round($n*0.2))" | python3)
	head -n $nval $dir/all/files > $dir/all/files_val
	tail -n +$(($nval+1)) $dir/all/files > $dir/all/files_train
	rm $dir/train/samples/*T*.nc || true
	rm $dir/val/samples/*T*.nc || true
	parallel ln -s ../../all/{/} $dir/train/samples/{/} :::: $dir/all/files_train
	parallel ln -s ../../all/{/} $dir/val/samples/{/} :::: $dir/all/files_val
	ds merge sample data/train/samples/*.nc data/train/all.nc
	ds merge sample data/val/samples/*.nc data/val/all.nc
	;;

train)
	bin/ann train data/{train,val,ann.h5,history.nc} nclasses: 30
	;;

apply)
	bin/ann apply data/{ann.h5,val,pred} nclasses: 30
	;;

*)
	echo "Invalid command \"$1\"" >&2
esac
